### ISSUE TITLE
Add Viewer Permissions

### ISSUE THREAD

**Issue by smitmad9** [OPEnSLab-OSU/Spool#15]
**Is your feature request related to a problem? Please describe.**
Unless a person is the owner of a network, they cannot see the devices or data logged with the device.

**Describe the solution you'd like**
Owner has the option to add a viewer. They can enter the intended viewer's email to check if they have an Auth0 account. If so, add the viewer's Auth0 id to the mongoDB document for the specific Network and Device. If not, invite them to create an account with Auth0.

**Describe alternatives you've considered**
N/A at this time.

**Additional context**

**Comment by eliwinkelman** [comment]
It would be nice to have a standard interface for assigning user permission to objects instead of a one-off solution. For example, a permissions class could store types of permissions ("edit", "view", etc.) and which users have them:
e.g. 
``` 
   {
      'edit': [user_ids],
      'view': [user_ids],
      'delete': [user_ids], etc.
}
```
and then just expose methods to add, remove, and check permissions for a user on an object.
e.g. `object.permissions.check('edit', user_id)` or `user.can('edit', object)`.
